#!/bin/sh

# 
# Clean solr repository 
#

exitWithUsage()
{
    echo "$1" 1>&2
    usage
    exit 1
}


usage()
{
    cat << EOF

USAGE: `basename $0` options

OPTIONS:
   --mode (optional - default:local ) [local|cloud]
   --help (optional)

EOF
}


init()
{
    MODE=

    while getopts ":-:" OPTION
    do
        LONG_OPTION="${OPTARG%%=*}"
        OPTARG="${OPTARG#*=}"

        case $LONG_OPTION in
            mode) 
                MODE=${OPTARG}
                ;;

            help) 
                usage ; 
                exit 0
                ;;

            *) 
                echo "Unknown option ${LONG_OPTION}" ; 
                usage ; 
                exit 1 
                ;;
        esac
    done

    if [ "${MODE}" != "local" ] && [ "${MODE}" != "cloud" ]; then
        exitWithUsage "unknwon value ${MODE} for option mode."
    fi

    . ~/.conf_solr
   
}


clean()
{

    if [ "${MODE}" = "cloud" ]; then
        echo "Clean and backup Remote solr cores ..."

        rm -rf ${REMOTE_SOLR_CORES_BCK} 
        mv     ${SOLR_CORES} ${REMOTE_SOLR_CORES_BCK} 2>/dev/null
    fi  

    echo "Clean Solr-${SOLR_VERSION} & Zookeeper-${ZOOKEEPER_VERSION} repositories at ${SEARCH_ROOT} ..."

    if [ ! -e ${SEARCH_ROOT} ]; then
        mkdir -p ${SEARCH_ROOT}
    fi  

    ${SOLR_ROOT}/stop && ${ZOOKEEPER_ROOT}/bin/zkServer.sh stop

    cd ${SEARCH_ROOT} && rm -rf solr-${SOLR_VERSION} && rm -rf zookeeper-${ZOOKEEPER_VERSION};      
}


init "$@"

clean
