#!/bin/sh

#
# Deploy Solr 
#

exitWithError ()
{
    echo "$1" 1>&2
    exit 1
}


exitWithUsage ()
{
    echo "$1" 1>&2
    usage
    exit 1
}


usage ()
{
    cat << EOF

USAGE: `basename $0` options

OPTIONS:
   --mode         (required) [local|cloud]
   --help         (optional) displays this message

EOF
}


init ()
{
    MODE=local

    while getopts ":-:" OPTION
    do
        LONG_OPTION="${OPTARG%%=*}"
        OPTARG="${OPTARG#*=}"

        case $LONG_OPTION in
            mode)
                MODE=${OPTARG}
                ;;

            help) 
                usage ; 
                exit 0
                ;;

            *) 
                echo "Unknown option ${LONG_OPTION}" ; 
                usage ; 
                exit 1 
                ;;
        esac
    done

    if [ "${MODE}" = "" ]; then
        exitWithUsage "a required option is missing."
    fi

    if  [ "${MODE}" != "local" ] && [ "${MODE}" != "cloud" ]; then
        exitWithUsage "unknown value ${MODE} for option mode."
    fi

    if [ "${MODE}" = "local" ]; then
        . conf/.conf_solr
        CONF_JAVA_FILE="set_conf_java.sh"
    else
        echo "to be continued ..."
    fi
}

install ()
{
    echo "Deploying Solr sources ..."

    if [ ! -e ${SOLR_ROOT} ]; then
        mkdir -p ${SOLR_ROOT}
    fi

    cp -r ../source_solr/solr-${SOLR_VERSION}/* ${SOLR_ROOT}/

    if [ ! -e ${SOLR_RUN} ]; then
        mkdir -p ${SOLR_RUN}
        touch ${SOLR_RUN}/jetty.pid
    fi

    if [ ! -e ${SOLR_LOGS} ]; then
        mkdir -p ${SOLR_LOGS}
    fi    

    cp ../source_solr/scripts/start   ${SOLR_ROOT}/
    cp ../source_solr/scripts/stop    ${SOLR_ROOT}/
    cp ../source_solr/scripts/restart ${SOLR_ROOT}/

    cp ../source_solr/conf/${CONF_JAVA_FILE} ${SOLR_ROOT}/

    if [ "${CONF_JAVA_FILE}" != "set_conf_java.sh" ]; then
        mv -f ${SOLR_ROOT}/${CONF_JAVA_FILE} ${SOLR_ROOT}/set_conf_java.sh
    fi
}

init "$@"

install
