#!/bin/sh

# 
# Deploy .conf_solr 
#

exitWithUsage()
{
    echo "$1" 1>&2
    usage
    exit 1
}


usage()
{
    cat << EOF

USAGE: `basename $0` options

OPTIONS:
   --mode (required) [local|cloud]
   --help (optional)

EOF
}


init()
{
    MODE=

    while getopts ":-:" OPTION
    do
        LONG_OPTION="${OPTARG%%=*}"
        OPTARG="${OPTARG#*=}"

        case $LONG_OPTION in
            mode) 
                MODE=${OPTARG}
                ;;

            help) 
                usage ; 
                exit 0
                ;;

            *) 
                echo "Unknown option ${LONG_OPTION}" ; 
                usage ; 
                exit 1 
                ;;
        esac
    done

    if [ "${MODE}" != "local" ] && [ "${MODE}" != "cloud" ]; then
        exitWithUsage "unknwon value ${MODE} for option mode."
    fi

    if [ "${MODE}" = "local" ]; then
        . conf/.conf_solr
    else
        . conf/.conf_solr_cloud
    fi    
}


push()
{

    cp -n ~/.conf_solr ~/.conf_solr_bck; 
    rm -f ~/.conf_solr;

    if [ "${MODE}" = "local" ]; then
        echo "Deploying .conf_solr ..."
        cp conf/.conf_solr ~/;
    else
        echo "Deploying .conf_solr_cloud ..."
        cp conf/.conf_solr_cloud ~/;
        ln -s ~/.conf_solr_cloud ~/.conf_solr 
    fi
}


init "$@"

push
